### ISSUE TITLE
基于netty的websocket疑问

### ISSUE THREAD

**Issue by weinierfei** [aLittleGreens/NettyDemo#10]
请问下楼主,netty在安卓上可以实现带参数的websocket长连接吗?类似于这样的ws://10.0.8.55:18888/websocket?uuid=" + 1000002 + "&sendSiteId=" + 6
好像这个参数没法传递啊

**Comment by aLittleGreens** [comment]
很抱歉，我也不了解

**Comment by weinierfei** [comment]
好的 感谢回复 我在试试
