### ISSUE TITLE
连接之后发送消息就直接断开连接了

### ISSUE THREAD

**Issue by sceneren** [aLittleGreens/NettyDemo#11]
能帮忙解决下吗？

**Comment by aLittleGreens** [comment]
断开，应该是服务器那边给你断开，客户端应该没问题

**Comment by sceneren** [comment]
能帮忙看看吗 这个问题 弄了好几天了 都没解决 ，可以给报酬  感谢

**Comment by aLittleGreens** [comment]
加我微信说下你的问题吧，微信号 cai784921129




------------------ 原始邮件 ------------------
发件人: "sceneren"<notifications@github.com>; 
发送时间: 2019年7月23日(星期二) 上午10:26
收件人: "aLittleGreens/NettyDemo"<NettyDemo@noreply.github.com>; 
抄送: "&杀狼的猪&"<784921129@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [aLittleGreens/NettyDemo] 连接之后发送消息就直接断开连接了 (#11)




能帮忙看看吗 这个问题 弄了好几天了 都没解决 ，可以给报酬  感谢

**Comment by sceneren** [comment]
加了 麻烦同意下

**Comment by aLittleGreens** [comment]
原因找到了，因为客户端发送消息与服务端约定的字段不一致，服务端匹配不到，是服务端断开了客户端连接，重新改用正确的消息字段，可解决。
